### ISSUE TITLE
Counting error? 

### ISSUE THREAD

**Issue by akondrahman** [brokenquark/SLIC-Ansible#16]
I was looking at this file `https://github.com/brokenquark/SLIC-Ansible/blob/master/smellsList/openstack.csv` and I noticed for `/home/brokenquark/Workspace/SLIC-Ansible (copy)/repo-openstack/openstack@monasca-vagrant/mini-mon.yml` the total count of smell is 20, of which 10 is from `hard-coded secrets`, and 5 from `hard-coded user name` and 5 from `hard-coded password` ... it should be 10 altogether ... why is it 20?

**Comment by rayhanur-rahman** [comment]
Besides username and passwords, there are a few other reasons that can lead to hardcoded-secret such as hardcoded ssh key locations. For example, look at the file `/home/brokenquark/Workspace/SLIC-Ansible (copy)/repo-openstack/openstack@ansible-role-container-registry/zuul.d/playbooks/pre.yml` and you will see that total = 4 while hardcoded_username = 0 and hardcoded_password = 0. I also manually checked the file as well.

I will still run the code later tonight to be 100% sure.
