### ISSUE TITLE
Collect repos

### ISSUE THREAD

**Issue by akondrahman** [brokenquark/SLIC-Ansible#2]
Need to collect Chef and Ansible repos from GitHub by using the filtering criteria
> Input: a CSV where the repo names are provided 
> output: a directory where a set of repos are specified that satisfy the follwoign criteria 
> needed for both Ansible and Chef 

- repo must not be a clone 
- repo should have two commits per month 
- repo should have 10% Chef scripts for Chef (recipes/*.rb), and 10% Ansible (.yml) scripts 
- repo shoild have at leaast 10 devs

**Comment by brokenquark** [comment]
chef cookbooks importing done

**Comment by akondrahman** [comment]
Can we meet on Friday (Mar 08) to discuss the next step?

**Comment by brokenquark** [comment]
Yes, why not... :) What's the time...???
RIght now, am collecting Ansible playbooks. The repo list is huge... :(
